function define(name, value) {
	Object.defineProperty(exports, name, {
		value:      value,
		enumerable: true
	});
}

define("first_name_ar", "first_name_ar");
define("first_name_en", "first_name_en");
define("first_name", "first_name");

define("STATUS_SUCCESS", "0");
define("RES_STATUS_ZERO", 0);
define("RES_STATUS_ONE", 1);
define("RES_STATUS_TWO", 2);
define("RES_STATUS_THREE", 3);
define("RES_STATUS_FOUR", 4);
define("RES_STATUS_FIVE", 5);
define("RES_STATUS_SIX", 6);

//Error codes
define("ERROR_STATUS_WATSON_FAILED", "40");
define("ERROR_STATUS_WATSON_FORMAT_FAILED", "41");
define("ERROR_STATUS_CONFIG_FAILED", "42");
define("ERROR_STATUS_CONFIG_QUERY_FAILED", "43");
define("ERROR_STATUS_QUERY_NO_RESULT", "44");
define("ERROR_STATUS_QUERY_FAILED", "45");
define("ERROR_STATUS_DIALOGUE_TPL_FAILED", "46");
define("ERROR_STATUS_INVALID_INTENT", "47");
define("ERROR_STATUS_INVALID_DB_URL", "48");
define("ERROR_STATUS_CONTEXT_FAILED", "49");
define("ERROR_STATUS_TECH_FAILED", "4A");
define("ERROR_STATUS_INVALID_INPUT", "4B");
define("ERROR_STATUS_JSON_PARSE_ERROR", "4C");
define("ERROR_STATUS_INVALID_HTTP_METHOD", "4D");
define("ERROR_STATUS_UNSUPPORTED_LANGUAGE", "4E");
define("ERROR_MICROBOT_RESPONSE_ERROR", "4F");
define("ERROR_STATUS_MAP_XML_NOT_FOUND", "4G");
define("ERROR_STATUS_MICROBOT_CALL_ERROR", "4H");
define("ERROR_STATUS_INVALID_USER_PWD", "4I");
define("ERROR_STATUS_UNSUPPORTED_INTENT", "4J");
define("ERROR_STATUS_TPL_LOADING_FAILED", "4K");
define("ERROR_STATUS_TPL_LOADING_NO_RESULT", "4L");
define("ERROR_STATUS_DISLIKE_REASON_URL_UNREACHABLE", "4M");
define("ERROR_STATUS_LANGUAGES_NULL", "4N");
define("ERROR_STATUS_DIALOG_NULL", "4O");
define("ERROR_ACTION_HANDLER_NOT_FOUND", "4P");
define("ERROR_IN_CHECK_STUCT_INTENT", "4Q");
define("ERROR_IN_CHECK_GENERIC_INTENT", "4R");

//Decision status
define("DECISION_SUCCESS", 0);
define("DECISION_NO_INTENT_NO_ENTITY", 1);
define("DECISION_NO_INTENT_N_ENTITY", 2);
define("DECISION_ONE_INTENT_NO_ENTITY", 3);
define("DECISION_ONE_INTENT_N_ENTITY_NO_RESULT", 4);
define("DECISION_ILLEGAL_ENTITY", 6);
define("DECISION_FOLLOW_UP", 7);
define("DECISION_SEARCH_RESPONSE", 8);
define("DECISION_UNSUPPORTED_INTENT", 9);//
define("DECISION_NO_PERSONALISE", 10);
define("DECISION_NO_DATA", 12);
define("DECISION_ERROR", 11);


define("UNSUPPORTED_INTENT", "UNSUPPORTED_INTENT");
define("ILLEGAL_ENTITY_TYPE", 'Illegal');
define("ENTITY_TYPE", 'ENTITY_TYPE');
define("ENTITY_TYPE_BUILDING", 'Building');
define("ENTITY_TYPE_OFFICE", 'Office');
define("ENTITY_TYPE_PARKING", 'Parking');
define("ENTITY_TYPE_DINING", 'Dining');

//dialog rules and pick index 

define("Common", 0);
define("BOT_Orchestrator", 1);
define("BOT_Campus", 2);
define("BOT_PersonDirectory", 3);
define("BOT_FinancialAid", 4);
define("BOT_AcademicPerformance", 5);
define("BOT_ClassSchedule", 6);

define("DIALOGUE_RULE_ZERO", 0);
define("DIALOGUE_RULE_ONE", 1);
define("DIALOGUE_RULE_TWO", 2);
define("DIALOGUE_RULE_THREE", 3);
define("DIALOGUE_RULE_FOUR", 4);
define("DIALOGUE_RULE_FIVE", 5);
define("DIALOGUE_RULE_SIX", 6);
define("DIALOGUE_RULE_SEVEN", 7);
define("DIALOGUE_RULE_EIGHT", 8);

define("DIALOGUE_PICK_INDEX_ZERO", "0");
define("DIALOGUE_PICK_INDEX_ONE", "01");
define("DIALOGUE_PICK_INDEX_TWO", "02");
define("DIALOGUE_PICK_INDEX_THREE", "03");
define("DIALOGUE_PICK_INDEX_FOUR", "04");
define("DIALOGUE_PICK_INDEX_FIVE", "05");
define("DIALOGUE_PICK_INDEX_SIX", "06");
define("DIALOGUE_PICK_INDEX_SEVEN", "07");
define("DIALOGUE_PICK_INDEX_EIGHT", "08");
define("DIALOGUE_PICK_INDEX_NINE", "09");
define("DIALOGUE_PICK_INDEX_TEN", "10");
define("DIALOGUE_PICK_INDEX_ELEVEN", "11");
define("DIALOGUE_PICK_INDEX_TWELVE", "12");
define("DIALOGUE_PICK_INDEX_THIRTEEN", "13");
define("DIALOGUE_PICK_INDEX_FOURTEEN", "14");
define("DIALOGUE_PICK_INDEX_FIFTEEN", "15");
define("DIALOGUE_PICK_INDEX_SIXTEEN", "16");
define("DIALOGUE_PICK_INDEX_SEVENTEEN", "17");
define("DIALOGUE_PICK_INDEX_EIGHTEEN", "18");
define("DIALOGUE_PICK_INDEX_NINETEEN", "19");
define("DIALOGUE_PICK_INDEX_TWENTY", "20");
define("DIALOGUE_PICK_INDEX_TWENTY_ONE", "21");
define("DIALOGUE_PICK_INDEX_TWENTY_TWO", "22");
define("DIALOGUE_PICK_INDEX_TWENTY_THREE", "23");
define("DIALOGUE_PICK_INDEX_TWENTY_FOUR", "24");
define("DIALOGUE_PICK_INDEX_TWENTY_FIVE", "25");
define("DIALOGUE_PICK_INDEX_TWENTY_SIX", "26");
define("DIALOGUE_PICK_INDEX_TWENTY_SEVEN", "27");
define("DIALOGUE_PICK_INDEX_TWENTY_EIGHT", "28");
define("DIALOGUE_PICK_INDEX_TWENTY_NINE", "29");
define("DIALOGUE_PICK_INDEX_TWENTY_THIRTY", "30");
define("DIALOGUE_PICK_INDEX_THIRTY_ONE", "31");
define("DIALOGUE_PICK_INDEX_THIRTY_TWO", "32");
define("DIALOGUE_PICK_INDEX_THIRTY_THREE", "33");
define("DIALOGUE_PICK_INDEX_THIRTY_FOUR", "34");
define("DIALOGUE_PICK_INDEX_THIRTY_FIVE", "35");
define("DIALOGUE_PICK_INDEX_THIRTY_SIX", "36");
define("DIALOGUE_PICK_INDEX_THIRTY_SEVEN", "37");
define("DIALOGUE_PICK_INDEX_THIRTY_EIGHT", "38");
define("DIALOGUE_PICK_INDEX_THIRTY_NINE", "39");
define("DIALOGUE_PICK_INDEX_FORTY", "40");

//Configuration variables:
define("Environment", "ENVIRONMENT");
define("Version", "EBSP_VERSION");
define("Timezone", "TIMEZONE");
define("Timeout", "TIMEOUT");
define("AWSURL", "AWS_URL");
define("EBDSURL", "EBDS_URL");
define("ProxyURL", "PROXY_URL");
define("Index", "INDEX");
define("WorkspaceName", "WORKSPACE_NAME");
define("WorkspaceID", "WORKSPACE_ID");
define("WorkspaceUser", "WORKSPACE_USER");
define("WorkspacePwd", "WORKSPACE_PASSWORD");
define("WorkspaceVersionDate", "WORKSPACE_VERSION_DATE");
define("WorkspaceURL", "WORKSPACE_URL");
define("UniversityName", "UNIVERSITY_NAME");
define("UniversityURL", "UNIVERSITY_URL");
define("GoogleSearchURL", "GOOGLE_SEARCH_URL");
define("SearchUrlEN", "SEARCH_URL_EN");
define("SearchUrlAR", "SEARCH_URL_AR");
define("DATE_FORMAT", "DATE_FORMAT");
define("TIME_FORMAT", "TIME_FORMAT");
define("DATE_TIME_FORMAT", "DATE_TIME_FORMAT");
define("SUPPORTED_LANGUAGES", "SUPPORTED_LANGUAGES");
define("rankingRange", "RANKING_RANGE");
define("resultLimit", "RESULT_LIMIT");
define("enableFollowUpOptions", "ENABLE_FOLLOW_UP_OPTIONS");
define("defaultUserID", "DEFAULT_USERID");
define("ContextManagerURL", "CONTEXT_MANAGER_URL");
define("LoginURL", "LOGIN_URL");
define("LoginProxyURL", "LOGIN_PROXY_URL");
define("ProcessAgent", "PROCESS_AGENTS");
define("processAgentTxnId", "processAgentTxnId");
define("MICROBOT_AGENTS", "MICROBOT_AGENTS");
define("CallGetLikeDislikeReasonsURL", "CALL_GET_LIKEDISLIKE_REASONS_URL");
define("CallSaveLikeDislikeReasonsURL", "CALL_SAVE_LIKEDISLIKE_REASONS_URL");
define("UserInfoURL", "USER_INFO_URL");
define("ProxyAuth", "PROXY_AUTH");
define("GetNameByPersonID", "GET_NAME_BY_PERSONID");
define("GetUserInformation", "GET_USER_INFORMATION");
define("connectorURL", "CONNECTOR_URL");
define("connectorProxyURL", "CONNECTOR_PROXY_URL");
define("BotID", "BOT_ID");
define("FilterWords", "FILTER_WORDS");
define("BoostIntentRanking","BOOST_INTENT_RANKING");
define("BoostIntentRankingForAll", "BOOST_INTENT_RANKING_FOR_ALL");
define("considerSecondaryIntent", "CONSIDER_SECONDARY_INTENT");
define("CONSIDER_INTENT_FROM_CONTEXT", "CONSIDER_INTENT_FROM_CONTEXT");
define("NOUN_ENTITY_TYPE", "NOUN_ENTITY_TYPE");
define("isSpecialBot", "isSpecialBot");
define("allowedIntents", "allowedIntents");
define("allowedIntentsEnabled", "allowedIntentsEnabled");
define("INTENT_TIMING_UNSTRUCTURED", "INTENT_TIMING_UNSTRUCTURED");
define("INTENT_LC_UNSTRUCTURED", "INTENT_LC_UNSTRUCTURED");
define("GetTopRankSuggestions", "GetTopRankSuggestions");
define("FetchNudgesFromDataRecords", "FetchNudgesFromDataRecords");
define("IsPageContextRequired","IsPageContextRequired");
define("PageContextPattern","PageContextPattern");
define("IsSearchResultEnabled","IsSearchResultEnabled");
//------------------------//

//variables
define("COPIED_FROM", "COPIED_FROM");
define("ENTITY_PEOPLE", "People");
define("Orchestrator", "Orchestrator");
define("GMT", "GMT");
define("PlaceAnaphor", "PlaceAnaphor");
define("PersonalDataAnaphor", "PersonalDataAnaphor");
define("LocationAnaphor", "LocationAnaphor");

define("timezone", "timezone");
define("Name", "Name");
define("Campus", "Campus");
define("CampusVoice", "CAMPUS_VOICE");
define("Entites", "Entities");
define("Action", "Action");
define("Intents", "Intents");
define("Intent", "Intent");
define("StatusCode", "StatusCode");
define("statusCode", "statusCode");

define("ConversationID", "ConversationID");
define("Services", "Services");
define("Username", "Username");
define("Password", "Password");

define("RequestText", "RequestText");
define("RequestJSON", "RequestJSON");
define("ErrorDescription", "ErrorDescription");
define("ResponseDateTime", "ResponseDateTime");
define("ResponseJSON", "ResponseJSON");
define("ResponseText", "ResponseText");
define("UserID", "UserID");
define("EntitesObject", "EntitesObject");

define("Timing", "Timing");
define("GREETING_INTENT", "1_greeting");
define("ABOUT_BOT_INTENT", "1_about_us");
define("THANKS_INTENT", "1_thank_you");
define("GOOD_BYE_INTENT", "1_goodbye");
define("UNSTRUCTURED_INTENT", "unstructured");
define("STRUCTURED_ACADEMIC_EVENT", "academic-event");
define("STRUCTURED_TIMING", "timing");
define("STRUCTURED_LOCATION", "location");
define("DIFFERENCE_INTENT", "Difference");
define("IS_DIFFERENCE_INTENT", "IS_DIFFERENCE_INTENT");
define("GENERIC_INTENT", "GenericIntent");
define("PROMPT_A_QUESTION_INTENT", "1_prompt_a_question");
define("PROMPT_A_SYMPATHY_INTENT", "1_prompt_a_sympathy");
define("REPLY_A_STATUS_INTENT", "1_reply_a_status");
define("PRIMARY_ENTITY", "PRIMARY_ENTITY");

define("CONTEXT_GENDER", "CONTEXT_GENDER");
define("ContextPrefix", "ContextPrefix");
define("UserInfo", "UserInfo");
define("genderDesc", "gender_desc");
define("Gender_Postfix", " Student");

define("sensitive", "sensitive");
define("configs", "configs");
define("locationName", "locationName");
define("now", " now");
define("addtnlInputParams", "addtnlInputParams");
define("lat_lon", "lat_lon");
define("latitude", "latitude");
define("longitude", "longitude");
define("conversation_id", "conversation_id");
define("output", "output");
define("intents", "intents");
define("intent", "intent");
define("entities", "entities");
define("context", "context");
define("decision", "decision");
define("timeout", "timeout");
define("version", "version");
define("audit_service", "audit_service");
define("userAcadPlan", "userAcadPlan");
define("additionalPersistentInformation", "additionalPersistentInformation");
define("userDisplayName", "userDisplayName");
define("apiId", "apiId");
define("userId", "userId");
define("languageCode", "languageCode");
define("token", "token");
define("messageId", "messageId");
define("applicationId", "applicationId");
define("source", "source");
define("plan", "plan");
define("term", "term");
define("shortText", "shortText");
define("text", "text");
define("input", "input");
define("voice", "voice");
define("action", "action");
define("voiceonly", "voiceonly");
define("results", "results");
define("objects", "objects");
define("entity", "entity");
define("boost", "boost");
define("value", "value");
define("key", "key");
define("Structured", "Structured");
define("Generic", "GenericIntent");
define("type", "type");
define("intentsIdentified", "intentsIdentified");
define("primary", "primary");
define("secondary", "secondary");
define("handler", "handler");
define("Unstructured", "Unstructured");
define("FunctionalIntent", "FunctionalIntent");

define("changedBy", "changedBy");
define("ChangedBy", "ChangedBy");
define("ServedBy", "ServedBy");
define("servedBy", "servedBy");
define("RequestDateTime", "RequestDateTime");
define("DecisionStatus", "DecisionStatus");
define("CTX_LAN_VARS", "TEXT, VOICE, VOICE_ONLY, SHORT_TEXT");
define("MessageId", "MessageId");
define("START_DATE", "START_DATE");
define("END_DATE", "END_DATE");
define("TIME_ONE", "TIME_ONE");
define("TIME_TWO", "TIME_TWO");
define("DATE_ONE", "DATE_ONE");
define("DATE_TWO", "DATE_TWO");
define("TENSE", "TENSE");
define("PRESENT_TENSE", "is");
define("FUTURE_TENSE", "is");
define("PAST_TENSE", "was");
define("ENTITY_STATUS", "ENTITY_STATUS");
define("ENTITY_STATUS_CLOSED", "closed");
define("ENTITY_STATUS_OPEN", "open");
define("DEFAULT_LANGUAGE_CODE", "en");
define("DEFAULT_LANGUAGE_CODE_CAPS", "EN");
define("DEFAULT_USER_ID", "DEFAULT_USER_ID");
define("DEFAULT_TIMEZONE", "America/Denver");
define("EBSP", "EBSP");
define("TYPE", "TYPE");
define("ACTION_HANDLER", "ACTION_HANDLER");
define("ACTION_HANDLERS", "ACTION_HANDLERS");
define("EBSPURL", "EBSPURL");
define("INTENT_NAME", "INTENT_NAME");
define("ENTITY_VALUE", "ENTITY_VALUE");
define("ENTITY_LIST", "ENTITY_LIST");
define("DECISION_STATUS", "decisionStatus");
define("DIALOGUE_RULE", "dialogRule");
define("FINAL_RESPONSE", "FINAL_RESPONSE");

define("USERNAME", "USERNAME");
define("PASSWORD", "PASSWORD");
define("EBSP_VERSION", "EBSP_VERSION");
define("START_TIME", "CTX_RES_START_TIME");
define("START_TIME2", "CTX_RES_START_TIME2");
define("END_TIME2", "CTX_RES_END_TIME2");
define("CTX_RES_MEDIA", "CTX_RES_MEDIA");
define("CTX_RES_MON_START_TIME", "CTX_RES_MON_START_TIME");
define("CTX_RES_MON_END_TIME", "CTX_RES_MON_END_TIME");
define("CTX_RES_TUE_START_TIME", "CTX_RES_TUE_START_TIME");
define("CTX_RES_TUE_END_TIME", "CTX_RES_TUE_END_TIME");
define("CTX_RES_WED_START_TIME", "CTX_RES_WED_START_TIME");
define("CTX_RES_WED_END_TIME", "CTX_RES_WED_END_TIME");
define("CTX_RES_THU_START_TIME", "CTX_RES_THU_START_TIME");
define("CTX_RES_THU_END_TIME", "CTX_RES_THU_END_TIME");
define("CTX_RES_FRI_START_TIME", "CTX_RES_FRI_START_TIME");
define("CTX_RES_FRI_END_TIME", "CTX_RES_FRI_END_TIME");
define("CTX_RES_SAT_START_TIME", "CTX_RES_SAT_START_TIME");
define("CTX_RES_SAT_END_TIME", "CTX_RES_SAT_END_TIME");
define("CTX_RES_SUN_START_TIME", "CTX_RES_SUN_START_TIME");
define("CTX_RES_SUN_END_TIME", "CTX_RES_SUN_END_TIME");
define("CTX_RES_INTENT", "CTX_RES_INTENT");
define("CTX_RES_SECONDARY_INTENT", "CTX_RES_SECONDARY_INTENT");
define("CTX_RES_UNIQUE_ID", "CTX_RES_UNIQUE_ID");
define("CTX_RES_DAILOG_FLOW_ID", "CTX_RES_DIALOG_FLOW_ID");

define("dialogFlowID", "dialogFlowID");

define("END_TIME", "CTX_RES_END_TIME");
define("CTX_RES_DISTANCE", "CTX_RES_DISTANCE");
define("DIALOGUE_PICK_INDEX", "dialogPickIndex");
define("SECOND_DIALOGUE_PICK_INDEX", "SECOND_DIALOGUE_PICK_INDEX");
define("UNIVERSITY_URL", "UNIVERSITY_URL");
define("GOOGLE_SEARCH_URL", "GOOGLE_SEARCH_URL");
define("SEARCH_URL_EN", "SEARCH_URL_EN");
define("SEARCH_URL_AR", "SEARCH_URL_AR");
define("UNIVERSITY_NAME", "UNIVERSITY_NAME");
define("SUPPORTED_ENTITY_TYPES", "SUPPORTED_ENTITY_TYPES");
define("LANGUAGES", "LANGUAGES");
define("VALID_WITHOUT_ENTITY", "VALID_WITHOUT_ENTITY");
define("SEARCH_QUERY_DELIMITER", "SEARCH_QUERY_DELIMITER");

define("LEVEL_1_INTENT", "LEVEL_1_INTENT");
define("INTENT_LIST", "INTENT_LIST");
define("CLOSED_BUT_OPEN_BETWEEN", "Closed but open between ");
define("CLEAR_CONTEXT", "CLEAR_CONTEXT");
define("SET_CONTEXT", "SET_CONTEXT");
define("CONTEXT_INTENT_LIST", "intents_list");
define("CONTEXT_ENTITY_LIST", "entities_list");
define("SET_CONTEXT_TYPE", "SET_CONTEXT_TYPE");
define("RELAVANCE", "RELAVANCE");

define("INTENT_ENTITY_LIST_IN_CONTEXT", 1);
define("ENTITY_INTENT_LIST_IN_CONTEXT", 2);
define("ENTITY_IN_CONTEXT", 3);
define("EMPTY_CONTEXT", 4);

define("MATCH_UNKNOWN_ENTITY", '11');
define("MATCH_KNOWN_ENTITY", '10');
define("NO_MATCH_UNKNOWN_ENTITY", '01');
define("NO_MATCH_KNOWN_ENTITY", '00');
define("ZERO_INTENT_ZERO_ENTITY", "00");
define("ZERO_INTENT_ONE_ENTITY", "01");
define("ZERO_INTENT_N_ENTITY", "0n");
define("ONE_INTENT_ZERO_ENTITY", "10");
define("ONE_INTENT_ONE_ENTITY", "11");
define("ONE_INTENT_N_ENTITY", "1n");
define("N_INTENT_ZERO_ENTITY", "n0");
define("N_INTENT_ZERO_ENTITY", "n0");

define("TOTAL_NO_WEEKDAYS", 7);

define("AND", "and");
define("TO", "to");
define("TIME_TEXT", "TIME_TEXT");
define("UNDERSCORE_START_TIME", "_START_TIME");
define("UNDERSCORE_END_TIME", "_END_TIME");
define("SAMPLE_DATE", "2016-06-20");
define("APPEND", "APPEND");

define("sys_person", "sys_person");
define("SYS_PERSON", "sys-person");
define("sys_time", "sys-time");
define("sys_date_one", "sys_date_one");
define("sys_date_two", "sys_date_two");
define("sys_time_one", "sys_time_one");
define("sys_time_two", "sys_time_two");
define("sys_date_count", "sys_date_count");
define("sys_time_count", "sys_time_count");
define("curr_date", "curr_date");
define("curr_time", "curr_time");
define("ObjectTypeLocation", "3");
define("ObjectTypeTiming", "4");
define("ObjectTypePerson", "1");
define("ObjectTypeNone", "none");
define("ObjectTypeFollowUp", "followUp");
define("ObjectTypeGeneric", "non");
define("objType", "objType");
define("objectType", "objectType");
define("processAgent", "processAgent");
define("processAgentId", "processAgentId");
define("processId", "processId");
define("Template", "Template");
define("RANKING_RANGE", "RANKING_RANGE");
define("RESULT_LIMIT", "RESULT_LIMIT");
define("ACADEMIC_TERMS", "ACADEMIC_TERMS");
define("academicTerms", "academicTerms");
define("DISTANCE", "DISTANCE");

define("ENTITY_MATCHING", "ENTITY_MATCHING");
define("STEP_COUNTER", "STEP_COUNTER");
define("DYNAMIC_STEP_COUNTER", "DYNAMIC_STEP_COUNTER");
define("REF_URL", "REF_URL");
define("NOW_EXIST", "NOW_EXIST");
define("IS_ILLEGAL_ENTITY", "IS_ILLEGAL_ENTITY");
define("INTENT_ENTITY_BITS", "INTENT_ENTITY_BITS");
define("INTENT_ENTITY_VALIDATION", "INTENT_ENTITY_VALIDATION");
define("WCS_ENTITY_COUNT", "WCS_ENTITY_COUNT");
define("WCS_ENTITY_TYPE_LIST", "WCS_ENTITY_TYPE_LIST");
define("FIN_MAX_ENTITY_ALLOWED", 3);
define("WCS_ENTITY_LIST", "WCS_ENTITY_LIST");
define("PRIMARY_ENTITY_NAME", "ENTITY_NAME");
define("PRIMARY_ENTITY", "PRIMARY_ENTITY");
define("SECONDARY_ENTITY_NAME", "SECONDARY_ENTITY_NAME");
define("PRIMARY_ENTITY_TYPE", "PRIMARY_ENTITY_TYPE");
define("SECONDARY_ENTITY_MATCH", "KEYWORD");
define("SECONDARY_ENTITY_TYPE", "SECONDARY_ENTITY_TYPE");
define("VALIDATION_RES_COUNT", "VALIDATION_RES_COUNT");
define("UNIQUE_ID", "UNIQUE_ID");

define("CTX_RES", "CTX_RES");
define("CTX_RES_LATITUDE", "CTX_RES_LAT");
define("CTX_RES_LONGITUDE", "CTX_RES_LONG");
define("CTX_RES_VIDEO_URL", "CTX_RES_VIDEO_URL");
define("CTX_RES_REF_URL", "CTX_RES_REF_URL");
define("CTX_RES_SECONDARY_ENTITY", "CTX_RES_SECONDARY_ENTITY");
define("CTX_RES_KEYWORD", "CTX_RES_KEYWORD");
define("CTX_RES_COUNT", "CTX_RES_COUNT");
define("CTX_RES_TEXT", "CTX_RES_TEXT");
define("CTX_RES_VOICE", "CTX_RES_VOICE");
define("CTX_RES_VOICE_ONLY", "CTX_RES_VOICE_ONLY");
define("CTX_RES_SHORT_TEXT", "CTX_RES_SHORT_TEXT");
define("CTX_RES_ENTITY_NAME", "CTX_RES_ENTITY_NAME");
define("CTX_RES_LOCATION", "CTX_RES_VENUE");
define("CTX_RES_PRESENTER", "CTX_RES_PERSN_NAME");
define("CTX_RES_START_DATE", "CTX_RES_START_DATE");
define("CTX_RES_END_DATE", "CTX_RES_END_DATE");
define("CTX_RES_WEEKEND_START_TIME", "CTX_RES_WEEKEND_START_TIME");
define("CTX_RES_WEEKEND_END_TIME", "CTX_RES_WEEKEND_END_TIME");
define("CTX_RES_WEEKDAY_START_TIME", "CTX_RES_WEEKDAY_START_TIME");
define("CTX_RES_WEEKDAY_END_TIME", "CTX_RES_WEEKDAY_END_TIME");

define("CTX_RES_CUM_GPA", "CTX_RES_CUM_GPA");
define("CTX_RES_GRADE_FORGIVENESS_AVAILABLE", "CTX_RES_GRADE_FORGIVENESS_AVAILABLE");
define("CTX_RES_GRADE_FORGIVENESS_USED", "CTX_RES_GRADE_FORGIVENESS_USED");
define("CTX_RES_GRADE_FORGIVENESS_LIMIT", "CTX_RES_GRADE_FORGIVENESS_LIMIT");
define("CTX_RES_DEGREE_AUDIT_STATUS", "CTX_RES_DEGREE_AUDIT_STATUS");
define("CTX_RES_DEGREE_AUDIT_RUN_DATE", "CTX_RES_DEGREE_AUDIT_RUN_DATE");
define("CTX_RES_ACAD_STANDING", "CTX_RES_ACAD_STANDING");
define("CTX_RES_GPA", "CTX_RES_GPA");
define("CTX_RES_STATUS", "CTX_RES_STATUS");
define("CTX_RES_ACAD_LOAD", "CTX_RES_ACAD_LOAD");
define("CTX_RES_ACAD_LEVEL", "CTX_RES_ACAD_LEVEL");
define("CTX_RES_TOTAL_UNITS_COMPLETED", "CTX_RES_TOTAL_UNITS_COMPLETED");
define("CTX_RES_CWID", "CTX_RES_CWID");
define("CTX_RES_PROCESS_AGENT_ID", "CTX_RES_PROCESS_AGENT_ID");
define("CTX_RES_PROCESS_ID", "CTX_RES_PROCESS_ID");
define("CTX_RES_IS_DEFAULT", "CTX_RES_IS_DEFAULT");
define("IS_DEFAULT", "IS_DEFAULT");

define("DIALOGUE_TEMPLATE_DIR", "responseTemplate");

define("COUNT_SECONDARY_ENTITY_TYPE_MATCH", "COUNT_SECONDARY_ENTITY_TYPE_MATCH");
define("THREE_SECONDARY_ENTITY_TYPE_MATCH", 3);
define("TWO_SECONDARY_ENTITY_TYPE_MATCH", 2);
define("ONE_SECONDARY_ENTITY_TYPE_MATCH", 1);
define("NONE_SECONDARY_ENTITY_TYPE_MATCH", 0);

define("INTENT_FIRSTDAY", "FirstDay");
define("INTENT_LASTDAY", "LastDay");
define("INTENT_TIMING", "Timing");
define("INTENT_EVENTS", "Events");
define("INTENT_LOCATION", "Location");
define("INTENT_DESCRIPTION", "Description");
define("INTENT_CONTACT", "Contact");
define("INTENT_UNSTRUCTURED", "Unstructured");
define("INTENT_CAMPUS_EVENT", "CampusEvent");
define("INTENT_ALTERNATIVE", "Alternative");

define("ACTION_HANDLER_EVENTS", "Events");
define("ACTION_HANDLER_ASSIGNMENT_EVENTS", "Assignment");
define("ACTION_HANDLER_ACAD_EVENTS", "AcademicEvent");
define("ACTION_HANDLER_CAMPUS_EVENTS", "CampusEvent");
define("ACTION_HANDLER_STUDENT_PROFILE", "StudentProfile");
define("ACTION_HANDLER_PERSON", "Person");
define("ACTION_HANDLER_INSTRUCTION", "Instruction");
define("ACTION_HANDLER_TIMING_UNSTRUCTURED", "TimingUnstructured");
define("ACTION_HANDLER_LC_UNSTRUCTURED", "LCUnstructured");
define("ACTION_HANDLER_UNSTRUCTURED", "Unstructured");
define("ACTION_HANDLER_ALT_UNSTRUCTURED", "Alternate");
define("ACTION_HANDLER_LOCATION", "Location");
define("ACTION_HANDLER_CONTACT", "Contact");
define("ACTION_HANDLER_TIMING", "Timing");
define("ACTION_HANDLER_GENERIC_INTENT", "GenericIntent");

define("ENTITY_ASSIGNMENT_EVENTS", "Assignment");
define("ENTITY_ACADEMIC_EVENTS", "AcadEvent");
define("ENTITY_ACADEMIC_PROFILE", "AcademicProfile");
define("ENTITY_CAMPUS_EVENTS", "CampusEvent");
define("ENTITY_PEOPLE", "People");
define("SYSTEM_PERSON", "sys-person");
define("CAMPUS_LIBRARY", "Library");
define("CAMPUS_VENUE", "Venue");

define("DIALOGUE_PICK_FROM", "DIALOGUE_PICK_FROM");
define("DIALOGUE_PICK_FROM_COMMON_TEMPLATE", 1);
define("DIALOGUE_PICK_FROM_SPECIFIC_TEMPLATE", 2);


define("ONE_ENTITY", 1);
define("TWO_ENTITY", 2);
define("THREE_ENTITY", 3);

define("ZERO_RESULT", 0);
define("ONE_RESULT", 1);

define("NOTIFICATION_REQUEST", 2);

define("SP_ACADEMIC_STANDING", "Academic Standing");
define("SP_GOOD_STANDING", "Good Standing");
define("SP_ACADEMIC_PROBATION", "Academic Probation");
define("SP_GRADE_FORGIVENESS", "Grade Forgiveness");
define("SP_DEGREE_AUDIT", "Degree Audit");
define("SP_UDA_BLANK", "UDA Blank");
define("SP_GPA", "GPA");
define("SP_ACADEMIC_PROFILE", "Academic Profile");
define("SP_CREDITS", "Credits");
define("SP_GRADE", "Grade");
define("SP_USER_ID", "User Id");
define("SP_UNIT_STATUS", "Units Status");
define("SP_ACADEMIC_LOAD", "Academic Load");
define("SP_ACADEMIC_LEVEL", "Academic Level");
define("SP_Holds", "Holds");
define("SP_Do_I_Owe", "Do I Owe");
define("primaryKey", "primaryKey");

define("GPA_LIMIT", 2.5);
define("DEGREE_AUDIT_STATUS_ZERO", 0);
define("DEGREE_AUDIT_STATUS_ONE", 1);
define("DEGREE_AUDIT_STATUS_TWO", 2);

define("SEARCH_TYPE", 'SEARCH_TYPE');
define("SUCCESS_SEARCH", 0);
define("FALLBACK_SEARCH", 1);
define("GOOGLE_SEARCH", 2);
define("SECONDARY_LANGUAGE_EXIST", "SECONDARY_LANGUAGE_EXIST");
define("CONTEXTUAL_QUESTION", "CONTEXTUAL_QUESTION");
define("ORIGINAL_ENTITIES", "ORIGINAL_ENTITIES");
define("TOP_ENTITY_NAME", "TOP_ENTITY_NAME");
define("VIRTUAL_ENTITY_NAME", "VIRTUAL_ENTITY_NAME");
define("CONTEXT_ENTITY_NAME", "CONTEXT_ENTITY_NAME");
define("CTX_RES_MAP_URL", "CTX_RES_MAP_URL");
define("ENTITY_TYPE_CAMPUS_KEYWORD", "CampusKeyword");
define("ENTITY_TYPE_SPECIFIC_ACTION", "SpecificAction");
define("ENTITY_TYPE_ACTION", "Action");
define("CONTEXT_ENTITIES", "CONTEXT_ENTITIES");
define("WCS_ENTITIES", "WCS_ENTITIES");
define("FILTERED_TEXT_SEARCH", "FILTERED_TEXT_SEARCH");
define("FILTERED_TEXT", "FILTERED_TEXT");
define("literalEntities", "literalEntities");
define("literal", "literal");
define("EntityStatus", "EntityStatus");
define("NOT_APPLICABLE", "NA");
define("NA_RECORD", "NA_RECORD");
define("showFollowUp", "showFollowUp");
define("showNudges", "showNudges");
define("showSuggestion", "showSuggestion");
define("WCS_ENTITIES_RATIO", "WCS_ENTITIES_RATIO");

define("ENTITY_NAME", "ENTITY_NAME");
define("KEYWORD", "KEYWORD");
define("SECONDARY_ENTITY", "SECONDARY_ENTITY");

//API
define("API_CONVERSATION", "1");
define("API_NOTIFICATION", "2");
define("API_HELPER", "3");
define("API_USER_LOGIN", "4");
define("API_AGENT_BOT", "5");
define("API_LIKE_DISLIKE", "6");
define("API_SAVE_LIKE_DISLIKE", "7");
define("API_FOLLOW_UP_QUESTION", "8");

//
define("MAX_FOLLOW_UP_OPTIONS", 4);
define("POST_METHOD", "POST");
define("AH_NO_INTENT", "NoIntent");
define("NUDGE_OPTIONS", "nudgeOptions");
define("NUDGE_OPTIONS2", "nudgeOptions2");
define("NUDGE_OPTIONS1", "nudgeOptions1");
define("MERGE_ACROSS_INTENT_NUDGES", "MERGE_ACROSS_INTENT_NUDGES");
define("actual_sys_date_count", "actual_sys_date_count");
define("INTENT_ENTITY_COUNT", "INTENT_ENTITY_COUNT");

define("STEP_EXACT_SEARCH", 0);
define("STEP_PS_PLUS_KS", 1);
define("STEP_P_NOT_S", 10);
define("STEP_P_PLUS_K", 2);
define("STEP_CTX_PS_PLUS_KS", 3);
define("STEP_ONLY_S", 4);
define("STEP_OTHER_INTENT", 5);

define("SORTING_ASCENDING", 'asc');
define("SORTING_DESCENDING", 'desc');
define("ACTION_HANDLER_ORDER", 'ACTION_HANDLER_ORDER');
define("body", 'body');
define("CTX_RES_STEP_COUNTER", "CTX_RES_STEP_COUNTER");
define("nudgeEntities", "nudgeEntities");
define("dataRecord","dataRecord");
define("nudgeFollowUpId","nudgeFollowUpId");

define("temporaryStatus", "responseCategory");
define("NudgeAnswer", "NudgeAnswer");
define("others", "others");
define("key", "key");
define("resultIntent", "resultIntent");
define("resultType", "resultType");
define("ResponseCategorySuccess", "Success");
define("ResponseCategoryFollowUp", "FollowUp");
define("ResponseCategoryNudges", "Nudges");
define("ResponseCategoryNoEntity", "NoEntity");
define("ResponseCategoryGoogleSearch", "Search");
define("ResponseCategorySuggestion", "Suggestion");

define("decisionStatus", "decisionStatus");
define("responseStatus", "responseStatus");
define("applicationStatus", "applicationStatus");
define("errCode", "errCode");

define("WCS", "wcs");
define("CONTEXT", "context");
define("MIXED", "mixed");

define("INTENT_FROM", "INTENT_FROM");
define("ENTITY_FROM", "ENTITY_FROM");

define("WCS_INTENT", "WCS_INTENT");
define("ACROSS_INTENT", "ACROSS_INTENT");

define("HANDLER_UNSTRUCTURED_WITHIN_INTENT", "unstructuredWithinIntent");
define("HANDLER_UNSTRUCTURED_ACROSS_INTENT", "unstructuredAcrossIntent");
define("HANDLER_UNSTRUCTURED_DEFAULT", "defaultWithinIntent");
define("HANDLER_STRUCTURED_ACROSS_INTENT", "structuredAcrossIntent");
define("COPIED_FROM_DEFAULT", "Default");
define("GUEST_USER","0000");

define("INTENTS", "INTENTS");
define("INTENT_TYPE_STRUCTURED", "Structured");
define("INTENT_TYPE_UNSTRUCTURED", "Unstructured");
define("DESIGNATION", "Designation");
define("AllMatchQuery", "AllMatchQuery");
define("MostMatchQuery", "MostMatchQuery");
define("KeywordMatchQuery", "KeywordMatchQuery");
define("KeySecMatchQuery", "KeySecMatchQuery");
define("CampusMatchQuery", "CampusMatchQuery");
define("DefaultIntentQuery", "DefaultIntentQuery");
define("AcrossIntentQuery", "AcrossIntentQuery");
define("WithinIntentQuery", "WithinIntentQuery");
define("OnlySecondaryMatchQuery", "OnlySecondaryMatchQuery");
define("CommonMatchQuery", "CommonMatchQuery");
define("FollowUpStQuery", "FollowUpStQuery");
define("GenericIntentQuery", "GenericIntentQuery");
define("FollowUpUnstQuery", "FollowUpUnstQuery");
define("HandleStructuredIntent", "HandleStructuredIntent");
define("SearchedStructuredIntent", "SearchedStructuredIntent");
define("PRIMARY_INTENT", "PRIMARY_INTENT");
define("INTENT", "INTENT");
define("dataEntities", "dataEntities");
define("replace_keyword", "replace_keyword");
define("replace_secondary", "replace_secondary");
define("IS_DEFAULT_VALUE", 1);
define("SECONDARY_INTENT", "SECONDARY_INTENT");
define("structuredData", "structuredData");
define("unstructuredData", "unstructuredData");
define("IS_EXCEPTION_CASE", "IS_EXCEPTION_CASE");
define("NUMBER_OF_RECORDS", "NUMBER_OF_RECORDS");
define("HANDLER", "HANDLER");
define("CONTEXT_ENTITIES_OBJECT", "CONTEXT_ENTITIES_OBJECT");
define("VIRTUAL_ENTITY_ONE", "VIRTUAL_ENTITY_ONE");
define("VIRTUAL_ENTITY_TWO", "VIRTUAL_ENTITY_TWO");
define("IS_ALTERNATE", "IS_ALTERNATE");
define("CTX_RES_IS_ALTERNATE", "CTX_RES_IS_ALTERNATE");
define("ACTION_HANDLER_TYPE", "ACTION_HANDLER_TYPE");
define("CTX_RES_ACTION_HANDLER", "CTX_RES_ACTION_HANDLER");

define("bestAnswer", "bestAnswer");
define("selectedDataType", "selectedDataType");
define("structuredAcross", "structuredAcross");
define("unstructuredAcross", "unstructuredAcross");
define("isGenericMerge", "isGenericMerge");
define("searchType", "searchType");
define("structuredWithinIntent", "structuredWithinIntent");
define("structuredAcrossIntent", "structuredAcrossIntent");
define("unStructuredWithinIntent", "unStructuredWithinIntent");
define("unStructuredAcrossIntent", "unStructuredAcrossIntent");
define("searchWithEntityName", "searchWithEntityName");
define("uniqueID", "uniqueID");
define("MAX_INTENT_IN_CONTEXT", 3);
define("OBJECT_TYPE", "OBJECT_TYPE");
define("setIntentIdentification", "setIntentIdentification");
define("isDefault", "isDefault");
define("replace_alternate", "replace_alternate");
define("API_DEVICE_SYNC", "9");